In [1]:
import sqlite3
import pandas as pd
import numpy as np

In [2]:
conn = sqlite3.connect("../database/ecommerce.db")
customers= pd.read_sql_query("SELECT * FROM customers",conn)
products = pd.read_sql_query(
    "SELECT * FROM Products",
    conn
)
orders = pd.read_csv("../data/Orders.csv")
payments = pd.read_csv("../data/Payments.csv")

In [4]:
orders.shape
payments.shape

(20, 5)

In [6]:
orders.columns
products.columns

Index(['product_id', 'product_name', 'category', 'price', 'stock_quantity'], dtype='object')

In [7]:
merged = orders.merge(products,on= "product_id")

In [8]:
merged.head()

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,stock_quantity
0,1,1,1,1,2025-04-01,iPhone 15,Electronics,79999.0,50
1,2,2,6,2,2025-04-02,The Psychology of Money,Books,399.0,200
2,3,3,4,1,2025-04-03,Nike Running Shoes,Sports,4999.0,80
3,4,4,8,1,2025-04-04,Mixer Grinder,Home & Kitchen,3499.0,60
4,5,5,2,1,2025-04-05,Samsung Galaxy S24,Electronics,69999.0,45

In [9]:
#merged revenue feature
merged["revenue"]= (merged["quantity"]*merged["price"])

In [10]:
merged[["product_name","quantity","price","revenue"]].head()

              product_name  quantity    price  revenue
0                iPhone 15         1  79999.0  79999.0
1  The Psychology of Money         2    399.0    798.0
2       Nike Running Shoes         1   4999.0   4999.0
3            Mixer Grinder         1   3499.0   3499.0
4       Samsung Galaxy S24         1  69999.0  69999.0

In [11]:
merged["order_date"]=pd.to_datetime(merged["order_date"])

In [12]:
merged["order_date"].dtype

dtype('<M8[ns]')

In [13]:
merged["month"]=(merged["order_date"].dt.month)

In [14]:
merged["month_name"]=(merged["order_date"].dt.month_name())

In [15]:
merged["day_name"]=(merged["order_date"].dt.day_name())

In [16]:
merged["year"]=(merged["order_date"].dt.year)

In [17]:
merged["is_weekend"]=(merged["order_date"].dt.dayofweek>=5)

In [18]:
merged.head()

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,stock_quantity,revenue,month,month_name,day_name,year,is_weekend
0,1,1,1,1,2025-04-01,iPhone 15,Electronics,79999.0,50,79999.0,4,April,Tuesday,2025,False
1,2,2,6,2,2025-04-02,The Psychology of Money,Books,399.0,200,798.0,4,April,Wednesday,2025,False
2,3,3,4,1,2025-04-03,Nike Running Shoes,Sports,4999.0,80,4999.0,4,April,Thursday,2025,False
3,4,4,8,1,2025-04-04,Mixer Grinder,Home & Kitchen,3499.0,60,3499.0,4,April,Friday,2025,False
4,5,5,2,1,2025-04-05,Samsung Galaxy S24,Electronics,69999.0,45,69999.0,4,April,Saturday,2025,True